/* soapClient.c
   Generated by gSOAP 2.7.1 from gSOAP_proxy.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(soap)

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.1 2005-04-26 04:10:44 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_api__doGoogleSearch(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *q, int start, int maxResults, enum _Enum_1 filter, char *restrict_, enum _Enum_1 safeSearch, char *lr, char *ie, char *oe, struct api__doGoogleSearchResponse *response)
{	struct api__doGoogleSearch soap_tmp_api__doGoogleSearch;
	if (!soap_endpoint)
		soap_endpoint = "http://api.google.com/search/beta2";
	soap->encodingStyle = "";
	soap_tmp_api__doGoogleSearch.key = key;
	soap_tmp_api__doGoogleSearch.q = q;
	soap_tmp_api__doGoogleSearch.start = start;
	soap_tmp_api__doGoogleSearch.maxResults = maxResults;
	soap_tmp_api__doGoogleSearch.filter = filter;
	soap_tmp_api__doGoogleSearch.restrict_ = restrict_;
	soap_tmp_api__doGoogleSearch.safeSearch = safeSearch;
	soap_tmp_api__doGoogleSearch.lr = lr;
	soap_tmp_api__doGoogleSearch.ie = ie;
	soap_tmp_api__doGoogleSearch.oe = oe;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_api__doGoogleSearch(soap, &soap_tmp_api__doGoogleSearch);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_api__doGoogleSearch(soap, &soap_tmp_api__doGoogleSearch, "api:doGoogleSearch", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_api__doGoogleSearch(soap, &soap_tmp_api__doGoogleSearch, "api:doGoogleSearch", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_api__doGoogleSearchResponse(soap, response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_api__doGoogleSearchResponse(soap, response, "api:doGoogleSearchResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_resolve_attachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_api__doGetCachedPage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *url, struct xsd__base64Binary *_return)
{	struct api__doGetCachedPage soap_tmp_api__doGetCachedPage;
	struct api__doGetCachedPageResponse *soap_tmp_api__doGetCachedPageResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://api.google.com/search/beta2";
	soap->encodingStyle = "";
	soap_tmp_api__doGetCachedPage.key = key;
	soap_tmp_api__doGetCachedPage.url = url;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_api__doGetCachedPage(soap, &soap_tmp_api__doGetCachedPage);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_api__doGetCachedPage(soap, &soap_tmp_api__doGetCachedPage, "api:doGetCachedPage", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_api__doGetCachedPage(soap, &soap_tmp_api__doGetCachedPage, "api:doGetCachedPage", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_xsd__base64Binary(soap, _return);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_api__doGetCachedPageResponse = soap_get_api__doGetCachedPageResponse(soap, NULL, "api:doGetCachedPageResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_resolve_attachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_return && soap_tmp_api__doGetCachedPageResponse->_return)
		*_return = *soap_tmp_api__doGetCachedPageResponse->_return;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_api__doSpellingSuggestion(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *phrase, char **_return)
{	struct api__doSpellingSuggestion soap_tmp_api__doSpellingSuggestion;
	struct api__doSpellingSuggestionResponse *soap_tmp_api__doSpellingSuggestionResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://api.google.com/search/beta2";
	soap->encodingStyle = "";
	soap_tmp_api__doSpellingSuggestion.key = key;
	soap_tmp_api__doSpellingSuggestion.phrase = phrase;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_api__doSpellingSuggestion(soap, &soap_tmp_api__doSpellingSuggestion);
	soap_begin_count(soap);
	if (soap->mode & SOAP_IO_LENGTH)
	{	soap_envelope_begin_out(soap);
		soap_putheader(soap);
		soap_body_begin_out(soap);
		soap_put_api__doSpellingSuggestion(soap, &soap_tmp_api__doSpellingSuggestion, "api:doSpellingSuggestion", "");
		soap_body_end_out(soap);
		soap_envelope_end_out(soap);
	}
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_api__doSpellingSuggestion(soap, &soap_tmp_api__doSpellingSuggestion, "api:doSpellingSuggestion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	*_return = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_api__doSpellingSuggestionResponse = soap_get_api__doSpellingSuggestionResponse(soap, NULL, "api:doSpellingSuggestionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
#ifndef WITH_LEANER
	 || soap_resolve_attachments(soap)
#endif
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_return && soap_tmp_api__doSpellingSuggestionResponse->_return)
		*_return = *soap_tmp_api__doSpellingSuggestionResponse->_return;
	return soap_closesock(soap);
}

SOAP_END_NAMESPACE(soap)

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
